# Generated by Django 2.2.1 on 2019-06-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestForm',
            new_name='TestModel',
        ),
    ]
